/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.umc.data.api.dto.server.UserInfoEditResultDTO

import com.squareup.moshi.Json

/**
 * 
 *
 * @param isSuccess 
 * @param code 
 * @param message 
 * @param result 
 */


data class ApiResponseUserInfoEditResultDTO (

    @Json(name = "isSuccess")
    val isSuccess: kotlin.Boolean? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "result")
    val result: UserInfoEditResultDTO? = null

)

