/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.umc.data.api.dto.server.ItemEquipResultDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isSuccess 
 * @param code 
 * @param message 
 * @param result 
 */


data class ApiResponseItemEquipResultDTO (

    @Json(name = "isSuccess")
    val isSuccess: kotlin.Boolean? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "result")
    val result: ItemEquipResultDTO? = null

) {


}

