/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.squareup.moshi.Json

/**
 * 
 *
 * @param challengeList 
 */


data class ChallengeListResultDTO (

    @Json(name = "challengeList")
    val challengeList: kotlin.collections.List<ChallengeResultDTO>? = null

)

