/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param challengeId 
 * @param title 
 * @param content 
 * @param isCompleted 
 */


data class ChallengeResultDTO (

    @Json(name = "challengeId")
    val challengeId: kotlin.Long? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "isCompleted")
    val isCompleted: kotlin.Boolean? = null

) {


}

