/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.squareup.moshi.Json

/**
 * 
 *
 * @param choices 
 */


data class ChatGPTResponseDTO (

    @Json(name = "choices")
    val choices: kotlin.collections.List<Choice>? = null

)

