/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.umc.data.api.dto.server.Message

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param index 
 * @param message 
 * @param createdAt 
 */


data class Choice (

    @Json(name = "index")
    val index: kotlin.Int? = null,

    @Json(name = "message")
    val message: Message? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null

) {


}

