/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.squareup.moshi.Json

/**
 * 
 *
 * @param index 
 * @param message 
 */


data class Choice (

    @Json(name = "index")
    val index: kotlin.Int? = null,

    @Json(name = "message")
    val message: Message? = null

)

