/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param categoryName 
 * @param categoryColor 
 */


data class CreateCategoryDTO (

    @Json(name = "categoryName")
    val categoryName: kotlin.String? = null,

    @Json(name = "categoryColor")
    val categoryColor: CategoryColor? = null

) {

    /**
     * 
     *
     * Values: RED,ORANGE,YELLOW,GREEN,SKYBLUE,BLUE,INDIGO,VIOLET,BROWN,WHITE,PINK,BLACK
     */
    @JsonClass(generateAdapter = false)
    enum class CategoryColor(val value: kotlin.String) {
        @Json(name = "RED") RED("RED"),
        @Json(name = "ORANGE") ORANGE("ORANGE"),
        @Json(name = "YELLOW") YELLOW("YELLOW"),
        @Json(name = "GREEN") GREEN("GREEN"),
        @Json(name = "SKYBLUE") SKYBLUE("SKYBLUE"),
        @Json(name = "BLUE") BLUE("BLUE"),
        @Json(name = "INDIGO") INDIGO("INDIGO"),
        @Json(name = "VIOLET") VIOLET("VIOLET"),
        @Json(name = "BROWN") BROWN("BROWN"),
        @Json(name = "WHITE") WHITE("WHITE"),
        @Json(name = "PINK") PINK("PINK"),
        @Json(name = "BLACK") BLACK("BLACK");
    }

}

