/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param content 
 * @param createdAt 
 */


data class DiaryReSummarizeResponseDTO (

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null

) {


}

