/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json

/**
 * 
 *
 * @param createdAt 
 * @param summaryDiary 
 */


data class DiarySummaryResultDTO (

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "summaryDiary")
    val summaryDiary: kotlin.String? = null

)

