/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param content 
 * @param diaryCategoryId 
 */


data class EditDTO (

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "diaryCategoryId")
    val diaryCategoryId: kotlin.Long? = null

) {


}

