/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json

/**
 * 
 *
 * @param diaryId 
 * @param updatedAt 
 */


data class EditResultDTO (

    @Json(name = "diaryId")
    val diaryId: kotlin.Long? = null,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

)

