/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param nickname 
 * @param email 
 * @param profileImage 
 * @param point 
 */


data class EditRequestDTO (

    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "profileImage")
    val profileImage: kotlin.String? = null,

    @Json(name = "point")
    val point: kotlin.Long? = null

) {


}

