/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.umc.data.api.dto.server.FailChallengeResultDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param failChallengeList 
 */


data class FailChallengeListResultDTO (

    @Json(name = "failChallengeList")
    val failChallengeList: kotlin.collections.List<FailChallengeResultDTO>? = null

) {


}

