/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param diaryId 
 * @param diaryCategoryId 
 * @param categoryColor 
 * @param latitude 
 * @param longitude 
 * @param clusterId 
 */


data class FootprintDiaryDTO (

    @Json(name = "diaryId")
    val diaryId: kotlin.Long? = null,

    @Json(name = "diaryCategoryId")
    val diaryCategoryId: kotlin.Long? = null,

    @Json(name = "categoryColor")
    val categoryColor: kotlin.String? = null,

    @Json(name = "latitude")
    val latitude: kotlin.Double? = null,

    @Json(name = "longitude")
    val longitude: kotlin.Double? = null,

    @Json(name = "clusterId")
    val clusterId: kotlin.Long? = null,

    @Json(name = "isSingle")
    val isSingle: kotlin.Boolean? = null
)

