/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.umc.data.api.dto.server.FootprintDiaryDTO

import com.squareup.moshi.Json

/**
 * 
 *
 * @param footprintList 
 */


data class FootprintDiaryListDTO (

    @Json(name = "footprintList")
    val footprintList: kotlin.collections.List<FootprintDiaryDTO>? = null

)

