/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.umc.data.api.dto.server.GetAllPastChallengeResultDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param getAllPastChallengeResultDTOList 
 */


data class GetAllPastChallengeListResultDTO (

    @Json(name = "getAllPastChallengeResultDTOList")
    val getAllPastChallengeResultDTOList: kotlin.collections.List<GetAllPastChallengeResultDTO>? = null

) {


}

