/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.umc.data.api.dto.server.ChallengeRemindAlarm
import com.umc.data.api.dto.server.DailySummaryAlarm
import com.umc.data.api.dto.server.MemoryDiaryAlarm
import com.umc.data.api.dto.server.WritingDiaryAlarm

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param writingDiaryAlarm 
 * @param memoryDiaryAlarm 
 * @param challengeRemindAlarm 
 * @param dailySummaryAlarm 
 */


data class GetAllAlarmsResponseDTO (

    @Json(name = "writingDiaryAlarm")
    val writingDiaryAlarm: WritingDiaryAlarm? = null,

    @Json(name = "memoryDiaryAlarm")
    val memoryDiaryAlarm: MemoryDiaryAlarm? = null,

    @Json(name = "challengeRemindAlarm")
    val challengeRemindAlarm: ChallengeRemindAlarm? = null,

    @Json(name = "dailySummaryAlarm")
    val dailySummaryAlarm: DailySummaryAlarm? = null

) {


}

