/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.umc.data.api.dto.server.CategoryDetailDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param categoryDetails 
 * @param totalDiaryCount 
 */


data class GetAllCategoryCountResultDTO (

    @Json(name = "categoryDetails")
    val categoryDetails: kotlin.collections.List<CategoryDetailDTO>? = null,

    @Json(name = "totalDiaryCount")
    val totalDiaryCount: kotlin.Int? = null

) {


}

