/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.umc.data.api.dto.server.IdDTO

import com.squareup.moshi.Json

/**
 * 
 *
 * @param idList 
 */


data class IdListDTO (

    @Json(name = "idList")
    val idList: kotlin.collections.List<IdDTO>? = null

)

