/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.umc.data.api.dto.server.ItemShopDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param point 
 * @param itemShopList 
 */


data class ItemShopListDTO (

    @Json(name = "point")
    val point: kotlin.Long? = null,

    @Json(name = "itemShopList")
    val itemShopList: kotlin.collections.List<ItemShopDTO>? = null

) {


}

