/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server

import com.umc.data.api.dto.server.ItemMyItemDTO

import com.squareup.moshi.Json

/**
 * 
 *
 * @param point 
 * @param myItemList 
 */


data class ItemMyItemListDTO (

    @Json(name = "point")
    val point: kotlin.Long? = null,

    @Json(name = "myItemList")
    val myItemList: kotlin.collections.List<ItemMyItemDTO>? = null

)

