/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isBought 
 * @param itemId 
 * @param point 
 * @param cost 
 */


data class ItemBuyResultDTO (

    @Json(name = "isBought")
    val isBought: kotlin.Boolean? = null,

    @Json(name = "itemId")
    val itemId: kotlin.Long? = null,

    @Json(name = "point")
    val point: kotlin.Long? = null,

    @Json(name = "cost")
    val cost: kotlin.Long? = null

)

