/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param itemId 
 * @param isEquipped 
 */


data class ItemEquipResultDTO (

    @Json(name = "itemId")
    val itemId: kotlin.Long? = null,

    @Json(name = "isEquipped")
    val isEquipped: kotlin.Boolean? = null

)

