/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param itemUniqueId 
 * @param name 
 * @param cost 
 * @param characterType 
 * @param bodyPart 
 */


data class MakeItemDTO (

    @Json(name = "itemUniqueId")
    val itemUniqueId: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "cost")
    val cost: kotlin.Long? = null,

    @Json(name = "characterType")
    val characterType: MakeItemDTO.CharacterType? = null,

    @Json(name = "bodyPart")
    val bodyPart: MakeItemDTO.BodyPart? = null

) {

    /**
     * 
     *
     * Values: TTUTTU,TTOTTO
     */
    @JsonClass(generateAdapter = false)
    enum class CharacterType(val value: kotlin.String) {
        @Json(name = "TTUTTU") TTUTTU("TTUTTU"),
        @Json(name = "TTOTTO") TTOTTO("TTOTTO");
    }
    /**
     * 
     *
     * Values: HEAD,TORSO
     */
    @JsonClass(generateAdapter = false)
    enum class BodyPart(val value: kotlin.String) {
        @Json(name = "HEAD") HEAD("HEAD"),
        @Json(name = "TORSO") TORSO("TORSO");
    }

}

