/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param diaryId 
 * @param diaryCategoryId 
 * @param date 
 * @param content 
 * @param image 
 * @param color 
 * @param firstDiary 
 * @param lastDiary 
 */


data class MapResultDTO (

    @Json(name = "diaryId")
    val diaryId: kotlin.Long? = null,

    @Json(name = "diaryCategoryId")
    val diaryCategoryId: kotlin.Long? = null,

    @Json(name = "date")
    val date: java.time.OffsetDateTime? = null,

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "image")
    val image: kotlin.String? = null,

    @Json(name = "color")
    val color: MapResultDTO.Color? = null,

    @Json(name = "firstDiary")
    val firstDiary: kotlin.Boolean? = null,

    @Json(name = "lastDiary")
    val lastDiary: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: RED,ORANGE,YELLOW,GREEN,SKYBLUE,BLUE,INDIGO,VIOLET,BROWN,WHITE,PINK,BLACK
     */
    @JsonClass(generateAdapter = false)
    enum class Color(val value: kotlin.String) {
        @Json(name = "RED") RED("RED"),
        @Json(name = "ORANGE") ORANGE("ORANGE"),
        @Json(name = "YELLOW") YELLOW("YELLOW"),
        @Json(name = "GREEN") GREEN("GREEN"),
        @Json(name = "SKYBLUE") SKYBLUE("SKYBLUE"),
        @Json(name = "BLUE") BLUE("BLUE"),
        @Json(name = "INDIGO") INDIGO("INDIGO"),
        @Json(name = "VIOLET") VIOLET("VIOLET"),
        @Json(name = "BROWN") BROWN("BROWN"),
        @Json(name = "WHITE") WHITE("WHITE"),
        @Json(name = "PINK") PINK("PINK"),
        @Json(name = "BLACK") BLACK("BLACK");
    }

}

