/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isActive 
 */


data class MemoryDiaryAlarm (

    @Json(name = "isActive")
    val isActive: MemoryDiaryAlarm.IsActive? = null

) {

    /**
     * 
     *
     * Values: ON,OFF
     */
    @JsonClass(generateAdapter = false)
    enum class IsActive(val value: kotlin.String) {
        @Json(name = "ON") ON("ON"),
        @Json(name = "OFF") OFF("OFF");
    }

}

