/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param categoryName 
 * @param categoryColor 
 */


data class ModifyCategoryDTO (

    @Json(name = "categoryName")
    val categoryName: kotlin.String? = null,

    @Json(name = "categoryColor")
    val categoryColor: kotlin.String? = null

) {


}

