/**
 * Ttatta BE API
 * 따따 백엔드 API 명세서
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.umc.data.api.dto.server


/**
 *
 * @param diaryCategoryId
 * @param content
 * @param date
 * @param latitude
 * @param longitude
 * @param locationName
 */
data class PostDTO(

    val diaryCategoryId: Long? = null,
    val content: String? = null,
    val date: java.time.LocalDateTime? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val locationName: String? = null
)