/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param diaryCategoryId 
 * @param content 
 * @param date 
 * @param latitude 
 * @param longitude 
 * @param locationName 
 * @param objectKey 
 */


data class PostDTO (

    @Json(name = "diaryCategoryId")
    val diaryCategoryId: kotlin.Long? = null,

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "date")
    val date: java.time.OffsetDateTime? = null,

    @Json(name = "latitude")
    val latitude: kotlin.Double? = null,

    @Json(name = "longitude")
    val longitude: kotlin.Double? = null,

    @Json(name = "locationName")
    val locationName: kotlin.String? = null,

    @Json(name = "objectKey")
    val objectKey: kotlin.String? = null

) {


}

