/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param presignedUrl 
 * @param objectKey 
 */


data class PresignedResultDTO (

    @Json(name = "presignedUrl")
    val presignedUrl: kotlin.String? = null,

    @Json(name = "objectKey")
    val objectKey: kotlin.String? = null

) {


}

