/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param diaryId 
 * @param diaryCategoryId 
 * @param date 
 * @param content 
 * @param image 
 * @param locationName 
 */


data class SearchDiaryDTO (

    @Json(name = "diaryId")
    val diaryId: kotlin.Long? = null,

    @Json(name = "diaryCategoryId")
    val diaryCategoryId: kotlin.Long? = null,

    @Json(name = "date")
    val date: java.time.OffsetDateTime? = null,

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "image")
    val image: kotlin.String? = null,

    @Json(name = "locationName")
    val locationName: kotlin.String? = null

)

