/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param email 
 * @param nickname 
 * @param username 
 * @param password 
 */


data class SignUpRequestDTO (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "nickname")
    val nickname: kotlin.String,

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String

)

