/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isRegistered 
 * @param accessToken 
 * @param refreshToken 
 */


data class TokenValidationResultDTO (

    @Json(name = "isRegistered")
    val isRegistered: kotlin.Boolean? = null,

    @Json(name = "accessToken")
    val accessToken: kotlin.String? = null,

    @Json(name = "refreshToken")
    val refreshToken: kotlin.String? = null

)

