/**
 * Ttatta BE API
 * 따따 백엔드 API 명세서
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.umc.data.api.dto.server


/**
 *
 * @param userId
 * @param nickname
 * @param loginType
 * @param email
 * @param profileImg
 * @param point
 * @param status
 * @param gender
 * @param phoneNum
 */
data class UserInfoResultDTO(

    val userId: Long? = null,
    val nickname: String? = null,
    val loginType: LoginType? = null,
    val email: String? = null,
    val profileImg: String? = null,
    val point: Long? = null,
    val status: Status? = null,
    val gender: Gender? = null,
    val phoneNum: String? = null
) {
    /**
     *
     * Values: REGULAR,KAKAO
     */
    enum class LoginType(val value: String) {
        REGULAR("REGULAR"),
        KAKAO("KAKAO");
    }

    /**
     *
     * Values: ACTIVE,INACTIVE
     */
    enum class Status(val value: String) {
        ACTIVE("ACTIVE"),
        INACTIVE("INACTIVE");
    }

    /**
     *
     * Values: MALE,FEMALE
     */
    enum class Gender(val value: String) {
        MALE("MALE"),
        FEMALE("FEMALE");
    }
}