/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 
 * @param nickname 
 * @param loginType 
 * @param email 
 * @param profileImg 
 * @param point 
 * @param status 
 * @param gender 
 */


data class UserInfoEditResultDTO (

    @Json(name = "userId")
    val userId: kotlin.Long? = null,

    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    @Json(name = "loginType")
    val loginType: LoginType? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "profileImg")
    val profileImg: kotlin.String? = null,

    @Json(name = "point")
    val point: kotlin.Long? = null,

    @Json(name = "status")
    val status: Status? = null,

    @Json(name = "gender")
    val gender: Gender? = null

) {

    /**
     * 
     *
     * Values: REGULAR,KAKAO
     */
    @JsonClass(generateAdapter = false)
    enum class LoginType(val value: kotlin.String) {
        @Json(name = "REGULAR") REGULAR("REGULAR"),
        @Json(name = "KAKAO") KAKAO("KAKAO");
    }
    /**
     * 
     *
     * Values: ACTIVE,INACTIVE
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "ACTIVE") ACTIVE("ACTIVE"),
        @Json(name = "INACTIVE") INACTIVE("INACTIVE");
    }
    /**
     * 
     *
     * Values: MALE,FEMALE
     */
    @JsonClass(generateAdapter = false)
    enum class Gender(val value: kotlin.String) {
        @Json(name = "MALE") MALE("MALE"),
        @Json(name = "FEMALE") FEMALE("FEMALE");
    }

}

