/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param reason 
 * @param withdrawnAt 
 * @param activeDays 
 * @param totalDiary 
 */


data class UserDeleteResultDTO (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "reason")
    val reason: kotlin.String? = null,

    @Json(name = "withdrawnAt")
    val withdrawnAt: java.time.OffsetDateTime? = null,

    @Json(name = "activeDays")
    val activeDays: kotlin.Int? = null,

    @Json(name = "totalDiary")
    val totalDiary: kotlin.Int? = null

) {


}

