/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 * @param userId 
 * @param nickname 
 * @param loginType 
 * @param createdAt 
 */


data class UserSignInResultDTO (

    @Json(name = "accessToken")
    val accessToken: kotlin.String? = null,

    @Json(name = "refreshToken")
    val refreshToken: kotlin.String? = null,

    @Json(name = "userId")
    val userId: kotlin.Long? = null,

    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    @Json(name = "loginType")
    val loginType: LoginType? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: REGULAR,KAKAO
     */
    @JsonClass(generateAdapter = false)
    enum class LoginType(val value: kotlin.String) {
        @Json(name = "REGULAR") REGULAR("REGULAR"),
        @Json(name = "KAKAO") KAKAO("KAKAO");
    }

}

