/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isAvailable 
 */


data class VerifyUsernameOverlapResultDTO (

    @Json(name = "isAvailable")
    val isAvailable: IsAvailable? = null

) {

    /**
     * 
     *
     * Values: AVAILABLE,UNAVAILABLE
     */
    @JsonClass(generateAdapter = false)
    enum class IsAvailable(val value: kotlin.String) {
        @Json(name = "AVAILABLE") AVAILABLE("AVAILABLE"),
        @Json(name = "UNAVAILABLE") UNAVAILABLE("UNAVAILABLE");
    }

}

