/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.umc.data.api.dto.server


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lng1 
 * @param lat1 
 * @param lng2 
 * @param lat2 
 * @param lng3 
 * @param lat3 
 * @param lng4 
 * @param lat4 
 */


data class ViewOnMapDTO (

    @Json(name = "lng1")
    val lng1: kotlin.Double? = null,

    @Json(name = "lat1")
    val lat1: kotlin.Double? = null,

    @Json(name = "lng2")
    val lng2: kotlin.Double? = null,

    @Json(name = "lat2")
    val lat2: kotlin.Double? = null,

    @Json(name = "lng3")
    val lng3: kotlin.Double? = null,

    @Json(name = "lat3")
    val lat3: kotlin.Double? = null,

    @Json(name = "lng4")
    val lng4: kotlin.Double? = null,

    @Json(name = "lat4")
    val lat4: kotlin.Double? = null

) {


}

