package com.umc.footprint.util

import androidx.compose.ui.graphics.Path

/**
 * SVG 경로 데이터를 파싱하여 Path를 반환합니다.
 * Generated by Gemini-2.5-Pro
 *
 * @param path SVG 'd' 속성 문자열.
 */
fun convertSvgPathToPath(path: String): Path {
    val tokens = tokenizeSvgPathData(path)
    val commands = parseSvgCommands(tokens)

    if (commands.isEmpty()) {
        throw IllegalArgumentException("No valid commands parsed from pathData.")
    }

    val path = Path()

    var currentX = 0f
    var currentY = 0f
    var lastCubicControlX = 0f
    var lastCubicControlY = 0f
    var lastQuadControlX = 0f
    var lastQuadControlY = 0f

    // 하위 경로의 시작점 (Z, z 명령어용)
    var subPathStartX = 0f
    var subPathStartY = 0f

    // 마지막으로 처리된 곡선 관련 명령어 유형 (S, T 명령어의 제어점 반사 로직용)
    var lastCurveCommandType: Char? = null


    for (command in commands) {
        val params = command.params
        val type = command.type

        // 현재 명령 실행 전의 좌표 (상대 좌표 계산 및 제어점 저장용)
        val prevCurrentX = currentX
        val prevCurrentY = currentY

        when (type) {
            'M' -> {
                currentX = params[0]; currentY = params[1]
                path.moveTo(currentX, currentY)
                subPathStartX = currentX; subPathStartY = currentY
            }

            'm' -> {
                currentX += params[0]; currentY += params[1]
                path.relativeMoveTo(params[0], params[1])
                subPathStartX = currentX; subPathStartY = currentY
            }

            'L' -> {
                currentX = params[0]; currentY = params[1]
                path.lineTo(currentX, currentY)
            }

            'l' -> {
                path.relativeLineTo(params[0], params[1])
                currentX += params[0]; currentY += params[1]
            }

            'H' -> {
                currentX = params[0]
                path.lineTo(currentX, prevCurrentY) // Y는 이전 값 사용
            }

            'h' -> {
                path.relativeLineTo(params[0], 0f)
                currentX += params[0]
            }

            'V' -> {
                currentY = params[0]
                path.lineTo(prevCurrentX, currentY) // X는 이전 값 사용
            }

            'v' -> {
                path.relativeLineTo(0f, params[0])
                currentY += params[0]
            }

            'C' -> { // x1 y1 x2 y2 x y
                path.cubicTo(params[0], params[1], params[2], params[3], params[4], params[5])
                lastCubicControlX = params[2]; lastCubicControlY = params[3] // 두 번째 제어점 저장 (절대)
                currentX = params[4]; currentY = params[5]
            }

            'c' -> { // dx1 dy1 dx2 dy2 dx dy
                path.relativeCubicTo(
                    params[0], params[1], params[2], params[3], params[4], params[5]
                )
                lastCubicControlX = prevCurrentX + params[2]; lastCubicControlY = prevCurrentY + params[3] // 두 번째 제어점 (절대 좌표로 변환하여 저장)
                currentX += params[4]; currentY += params[5]
            }

            'S' -> { // x2 y2 x y
                val c1X: Float
                val c1Y: Float
                if (lastCurveCommandType == 'C' || lastCurveCommandType == 'S') {
                    c1X = 2 * prevCurrentX - lastCubicControlX // 이전 제어점 반사
                    c1Y = 2 * prevCurrentY - lastCubicControlY
                } else {
                    c1X = prevCurrentX // 현재 점을 첫 번째 제어점으로 사용
                    c1Y = prevCurrentY
                }
                path.cubicTo(c1X, c1Y, params[0], params[1], params[2], params[3])
                lastCubicControlX = params[0]; lastCubicControlY = params[1] // 새로운 두 번째 제어점 저장
                currentX = params[2]; currentY = params[3]
            }

            's' -> { // dx2 dy2 dx dy
                val rc1X: Float // 첫 번째 제어점 (현재점에 대한 상대좌표)
                val rc1Y: Float
                if (lastCurveCommandType == 'C' || lastCurveCommandType == 'S') {
                    // lastCubicControlX, lastCubicControlY는 절대좌표
                    // 반사된 첫 번째 제어점 (절대): (2*prevCurrentX - lastCubicControlX, 2*prevCurrentY - lastCubicControlY)
                    // 상대 좌표로 변환: (2*prevCurrentX - lastCubicControlX) - prevCurrentX = prevCurrentX - lastCubicControlX
                    rc1X = prevCurrentX - lastCubicControlX
                    rc1Y = prevCurrentY - lastCubicControlY
                } else {
                    rc1X = 0f // 현재 점을 첫 번째 제어점으로 사용 (상대좌표 0,0)
                    rc1Y = 0f
                }
                path.relativeCubicTo(rc1X, rc1Y, params[0], params[1], params[2], params[3])
                lastCubicControlX = prevCurrentX + params[0] // 새로운 두 번째 제어점 (절대좌표로 변환하여 저장)
                lastCubicControlY = prevCurrentY + params[1]
                currentX += params[2]; currentY += params[3]
            }

            'Q' -> { // x1 y1 x y
                path.quadraticTo(params[0], params[1], params[2], params[3])
                lastQuadControlX = params[0]; lastQuadControlY = params[1] // 제어점 저장 (절대)
                currentX = params[2]; currentY = params[3]
            }

            'q' -> { // dx1 dy1 dx dy
                path.relativeQuadraticTo(params[0], params[1], params[2], params[3])
                lastQuadControlX = prevCurrentX + params[0]; lastQuadControlY = prevCurrentY + params[1] // 제어점 (절대좌표로 변환하여 저장)
                currentX += params[2]; currentY += params[3]
            }

            'T' -> { // x y
                val c1X: Float
                val c1Y: Float
                if (lastCurveCommandType == 'Q' || lastCurveCommandType == 'T') {
                    c1X = 2 * prevCurrentX - lastQuadControlX // 이전 제어점 반사
                    c1Y = 2 * prevCurrentY - lastQuadControlY
                } else {
                    c1X = prevCurrentX // 현재 점을 제어점으로 사용
                    c1Y = prevCurrentY
                }
                path.quadraticTo(c1X, c1Y, params[0], params[1])
                lastQuadControlX = c1X; lastQuadControlY = c1Y // 새로운 (반사된) 제어점 저장
                currentX = params[0]; currentY = params[1]
            }

            't' -> { // dx dy
                val rc1X: Float // 제어점 (현재점에 대한 상대좌표)
                val rc1Y: Float
                if (lastCurveCommandType == 'Q' || lastCurveCommandType == 'T') {
                    rc1X = prevCurrentX - lastQuadControlX
                    rc1Y = prevCurrentY - lastQuadControlY
                } else {
                    rc1X = 0f
                    rc1Y = 0f
                }
                path.relativeQuadraticTo(rc1X, rc1Y, params[0], params[1])
                lastQuadControlX = prevCurrentX + rc1X // 새로운 (반사된) 제어점 (절대좌표로 변환하여 저장)
                lastQuadControlY = prevCurrentY + rc1Y
                currentX += params[0]; currentY += params[1]
            }

            'A', 'a' -> {
                // SVG Arc ('A', 'a') 명령어는 Jetpack Compose의 arcTo와 직접 매핑되지 않습니다.
                // SVG Arc는 (rx, ry, xAxisRotate, largeArcFlag, sweepFlag, x, y) 파라미터를 사용하고,
                // Compose의 arcTo는 Rect, startAngle, sweepAngle을 사용합니다.
                // 이 변환은 매우 복잡하며 (W3C SVG Implementation Notes 참조),
                // 이 예제에서는 정확한 구현을 제공하지 않습니다.
                // 단순화를 위해 여기서는 최종점으로 직선을 그립니다.
                println("SVG Draw Warning: Arc command ('A'/'a') is complex and not fully implemented. Drawing lineTo endpoint instead.")
                if (params.size >= 7) {
                    if (type == 'A') {
                        currentX = params[5]; currentY = params[6]
                        path.lineTo(currentX, currentY)
                    } else { // 'a'
                        path.relativeLineTo(params[5], params[6])
                        currentX += params[5]; currentY += params[6]
                    }
                }
            }

            'Z', 'z' -> {
                path.close()
                // Z 명령어 후 현재 점은 하위 경로의 시작점으로 돌아감
                currentX = subPathStartX
                currentY = subPathStartY
            }

            else -> {
                // 알려지지 않은 명령어는 파서 단계에서 이미 경고 처리됨
            }
        }

        // 다음 S, T 명령어를 위해 현재 명령어 유형 업데이트
        lastCurveCommandType = if (type.uppercaseChar() in listOf('C', 'S', 'Q', 'T')) {
            type.uppercaseChar()
        } else {
            // 곡선 명령어가 아니면 반사 체인이 끊김
            null
        }
    }

    return path
}

// 파싱된 명령어를 나타내는 데이터 클래스
private data class SvgCommand(val type: Char, val params: List<Float>)

// 경로 데이터를 토큰(명령어 또는 숫자 문자열)으로 분리
private fun tokenizeSvgPathData(pathData: String): List<String> {
    val tokens = mutableListOf<String>()
    // 명령어 또는 숫자를 찾는 정규식 (지수 표기법 포함)
    val regex = """([aAcChHlLmMqQsStTvVzZ])|(-?\d+(?:\.\d+)?(?:[eE]-?\d+)?)""".toRegex()
    regex.findAll(pathData).forEach { matchResult ->
        tokens.add(matchResult.value)
    }
    return tokens
}

// 토큰 리스트를 SvgCommand 리스트로 파싱
private fun parseSvgCommands(tokens: List<String>): List<SvgCommand> {
    val commands = mutableListOf<SvgCommand>()
    var i = 0
    while (i < tokens.size) {
        val currentToken = tokens[i]
        val commandChar = currentToken[0]

        if (!commandChar.isLetter()) {
            // 경로 데이터는 반드시 명령어로 시작해야 함 (오류 처리 또는 무시)
            println("SVG Parse Warning: Expected a command character, but found '$currentToken'. Skipping.")
            i++
            continue
        }

        val paramsNeeded = when (commandChar.uppercaseChar()) {
            'Z' -> 0
            'H', 'V' -> 1
            'M', 'L', 'T' -> 2
            'S', 'Q' -> 4
            'C' -> 6
            'A' -> 7 // Elliptical Arc
            else -> {
                println("SVG Parse Warning: Unknown command '$commandChar'.")
                0 // 알 수 없는 명령어는 파라미터를 소비하지 않음
            }
        }

        val collectedParams = mutableListOf<Float>()
        var j = i + 1
        // 명령어에 필요한 만큼 파라미터 수집
        while (j < tokens.size && collectedParams.size < paramsNeeded) {
            try {
                tokens[j].toFloat() // 숫자인지 확인
                collectedParams.add(tokens[j].toFloat())
                j++
            } catch (_: NumberFormatException) {
                // 숫자가 아니면 다음 명령어로 간주하고 중단
                break
            }
        }

        // 하나의 명령어가 여러 좌표 세트를 가질 수 있는 경우 처리 (예: L x1 y1 x2 y2)
        // 첫 번째 명령과 파라미터 세트 추가
        if (collectedParams.size >= paramsNeeded && paramsNeeded > 0) {
            commands.add(SvgCommand(commandChar, collectedParams.subList(0, paramsNeeded)))
            // 나머지 파라미터 세트에 대해 암시적 명령으로 추가
            var k = paramsNeeded
            while (k + paramsNeeded <= collectedParams.size) {
                val nextParams = collectedParams.subList(k, k + paramsNeeded)
                // M 다음에는 L, m 다음에는 l로 처리
                val implicitCommandChar = when (commandChar) {
                    'M' -> 'L'
                    'm' -> 'l'
                    else -> commandChar // 다른 명령어는 동일하게 반복
                }
                commands.add(SvgCommand(implicitCommandChar, nextParams))
                k += paramsNeeded
            }
            i = j // j는 마지막으로 읽은 파라미터 다음 인덱스 또는 다음 명령어 인덱스
        } else if (paramsNeeded == 0) { // Z 명령어처럼 파라미터가 없는 경우
            commands.add(SvgCommand(commandChar, emptyList()))
            i++
        } else {
            // 파라미터가 부족한 경우 (오류 또는 다음 명령어로 간주)
            println("SVG Parse Warning: Not enough parameters for command '$commandChar'. Found ${collectedParams.size}, needed $paramsNeeded.")
            i = j // 다음 토큰으로 이동
        }
    }
    return commands
}