package com.umc.design.character

import androidx.annotation.RawRes
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import com.umc.design.R

enum class Accessory(
    val code: String,
    val title: String,
    val characterType: CharacterType,
    val bodyPart: BodyPart,
    @get:RawRes val equippedRes: Int,
    @get:RawRes val shopRes: Int,
    val offset: Offset,
    val size: Size,
    val isOverHand: Boolean = false,
) {
    TTOTTO_BAG(
        code = "TTOTTO_BAG",
        title = "또또의 가방",
        characterType = CharacterType.TTOTTO,
        bodyPart = BodyPart.TORSO,
        equippedRes = R.raw.img_ttotto_bag_equipped,
        shopRes = R.raw.img_ttotto_bag_shop,
        offset = Offset(29.74f, 54.1f),
        size = Size(118.96f, 92.88f),
    ),
    TTOTTO_CAP(
        code = "TTOTTO_CAP",
        title = "또또의 캡모자",
        characterType = CharacterType.TTOTTO,
        bodyPart = BodyPart.HEAD,
        equippedRes = R.raw.img_ttotto_cap_equipped,
        shopRes = R.raw.img_ttotto_cap_shop,
        offset = Offset(59.21f, -9f),
        size = Size(68f, 28f),
    ),
    TTOTTO_COZY_MUFFLER(
        code = "TTOTTO_COZY_MUFFLER",
        title = "또또의 포근한 머플러",
        characterType = CharacterType.TTOTTO,
        bodyPart = BodyPart.TORSO,
        equippedRes = R.raw.img_ttotto_cozy_muffler_equipped,
        shopRes = R.raw.img_ttotto_cozy_muffler_shop,
        offset = Offset(30.21f, 57f),
        size = Size(118f, 85f),
    ),
    TTOTTO_DND_EARPHONE(
        code = "TTOTTO_DND_EARPHONE",
        title = "또또의 방해금지 이어폰",
        characterType = CharacterType.TTOTTO,
        bodyPart = BodyPart.EYE,
        equippedRes = R.raw.img_ttotto_dnd_earphone_equipped,
        shopRes = R.raw.img_ttotto_dnd_earphones_shop,
        offset = Offset(16.68f, 34.97f),
        size = Size(152.6f, 22.29f),
    ),
    TTOTTO_HARDWORKING_LAPTOP(
        code = "TTOTTO_HARDWORKING_LAPTOP",
        title = "또또의 열일하는 노트북",
        characterType = CharacterType.TTOTTO,
        bodyPart = BodyPart.TORSO,
        equippedRes = R.raw.img_ttotto_hardworking_laptop_equipped,
        shopRes = R.raw.img_ttotto_hardworking_laptop_shop,
        offset = Offset(27.21f, 68.86f),
        size = Size(130f, 76f),
        isOverHand = true,
    ),
    TTOTTO_HAT(
        code = "TTOTTO_HAT",
        title = "또또의 모자",
        characterType = CharacterType.TTOTTO,
        bodyPart = BodyPart.HEAD,
        equippedRes = R.raw.img_ttotto_hat_equipped,
        shopRes = R.raw.img_ttotto_hat_shop,
        offset = Offset(32.43f, -2.67f),
        size = Size(53.37f,23.09f),
    ),
    TTOTTO_LOVELY_CAT(
        code = "TTOTTO_LOVELY_CAT",
        title = "또또의 사랑스러운 고양이",
        characterType = CharacterType.TTOTTO,
        bodyPart = BodyPart.HEAD,
        equippedRes = R.raw.img_ttotto_lovely_cat_equipped,
        shopRes = R.raw.img_ttotto_lovely_cat_shop,
        offset = Offset(61.21f, -26.14f),
        size = Size(93.99f,43f),
    ),
    TTOTTO_PUFFY_BACKPACK(
        code = "TTOTTO_PUFFY_BACKPACK",
        title = "또또의 빵빵한 백팩",
        characterType = CharacterType.TTOTTO,
        bodyPart = BodyPart.TORSO,
        equippedRes = R.raw.img_ttotto_puffy_backpack_equipped,
        shopRes = R.raw.img_ttotto_puffy_backpack_shop,
        offset = Offset(12.62f, 49.35f),
        size = Size(160.37f,132.08f),
        isOverHand = true,
    ),
    TTOTTO_SWEET_LEMON_CANDY(
        code = "TTOTTO_SWEET_LEMON_CANDY",
        title = "또또의 달콤한 레몬 사탕",
        characterType = CharacterType.TTOTTO,
        bodyPart = BodyPart.TORSO,
        equippedRes = R.raw.img_ttotto_sweet_lemon_candy_equipped,
        shopRes = R.raw.img_ttotto_sweet_lemon_candy_shop,
        offset = Offset(29.21f, 63.86f),
        size = Size(51f,51f),
    ),
    TTUTTU_BAG(
        code = "TTUTTU_BAG",
        title = "뚜뚜의 가방",
        characterType = CharacterType.TTUTTU,
        bodyPart = BodyPart.TORSO,
        equippedRes = R.raw.img_ttuttu_bag_equipped,
        shopRes = R.raw.img_ttuttu_bag_shop,
        offset = Offset(36.47f, 66.35f),
        size = Size(145.88f, 113.9f),
    ),
    TTUTTU_DOOMCHIT_HEADSET(
        code = "TTUTTU_DOOMCHIT_HEADSET",
        title = "뚜뚜의 둠칫 헤드셋",
        characterType = CharacterType.TTUTTU,
        bodyPart = BodyPart.HEAD,
        equippedRes = R.raw.img_ttuttu_doomchit_headset_equipped,
        shopRes = R.raw.img_ttuttu_doomchit_headset_shop,
        offset = Offset(20.89f, -2.98f),
        size = Size(186.56f, 71.97f),
    ),
    TTUTTU_GIANT_RIBBON(
        code = "TTUTTU_GIANT_RIBBON",
        title = "뚜뚜의 왕 큰 리본",
        characterType = CharacterType.TTUTTU,
        bodyPart = BodyPart.HEAD,
        equippedRes = R.raw.img_ttuttu_giant_ribbon_equipped,
        shopRes = R.raw.img_ttuttu_giant_ribbon_shop,
        offset = Offset(72f, -12f),
        size = Size(80.86f, 43.6f),
    ),
    TTUTTU_HAT(
        code = "TTUTTU_HAT",
        title = "뚜뚜의 모자",
        characterType = CharacterType.TTUTTU,
        bodyPart = BodyPart.HEAD,
        equippedRes = R.raw.img_ttuttu_hat_equipped,
        shopRes = R.raw.img_ttuttu_hat_shop,
        offset = Offset(39.77f, -3.31f),
        size = Size(65.45f, 28.31f),
    ),
    TTUTTU_LIFESAVER_COFFEE(
        code = "TTUTTU_LIFESAVER_COFFEE",
        title = "뚜뚜의 생명수 커피",
        characterType = CharacterType.TTUTTU,
        bodyPart = BodyPart.TORSO,
        equippedRes = R.raw.img_ttuttu_lifesaver_coffee_equipped,
        shopRes = R.raw.img_ttuttu_lifesaver_coffee_shop,
        offset = Offset(102.73f, 50.99f),
        size = Size(78.66f, 114f),
    ),
    TTUTTU_PERL_NECKLACE(
        code = "TTUTTU_PERL_NECKLACE",
        title = "뚜뚜의 진주 목걸이",
        characterType = CharacterType.TTUTTU,
        bodyPart = BodyPart.TORSO,
        equippedRes = R.raw.img_ttuttu_perl_necklace_equipped,
        shopRes = R.raw.img_ttuttu_perl_necklace_shop,
        offset = Offset(78f, 93f),
        size = Size(72.83f, 25f),
    ),
    TTUTTU_SNAP_CAMERA(
        code = "TTUTTU_SNAP_CAMERA",
        title = "뚜뚜의 찰칵 카메라",
        characterType = CharacterType.TTUTTU,
        bodyPart = BodyPart.TORSO,
        equippedRes = R.raw.img_ttuttu_snap_camera_equipped,
        shopRes = R.raw.img_ttuttu_snap_camera_shop,
        offset = Offset(31.5f, 60.49f),
        size = Size(166.3f, 139.7f),
    ),
    TTUTTU_SUNGLASSES(
        code = "TTUTTU_SUNGLASSES",
        title = "뚜뚜의 삐뚤어진 선글라스",
        characterType = CharacterType.TTUTTU,
        bodyPart = BodyPart.EYE,
        equippedRes = R.raw.img_ttuttu_sunglasses_equipped,
        shopRes = R.raw.img_ttuttu_sunglasses_shop,
        offset = Offset(59.08f, 43.91f),
        size = Size(106.53f, 40.88f),
    ),
    TTUTTU_TREASURED_DIARY(
        code = "TTUTTU_TREASURED_DIARY",
        title = "뚜뚜의 소중한 다이어리",
        characterType = CharacterType.TTUTTU,
        bodyPart = BodyPart.TORSO,
        equippedRes = R.raw.img_ttuttu_treasured_diary_equipped,
        shopRes = R.raw.img_ttuttu_treasured_diary_shop,
        offset = Offset(56f, 82f),
        size = Size(112.57f, 78.5f),
    ),
}
